function out1 = compose_pose_point_su2(lhs, rhs)
%COMPOSE_POSE_POINT_SU2
%    OUT1 = COMPOSE_POSE_POINT_SU2(LHS1,LHS2,LHS3,LHS4,LHS5,LHS6,LHS7,RHS1,RHS2,RHS3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    19-Feb-2019 09:00:04

lhs1 = lhs(1);
lhs2 = lhs(2);
lhs3 = lhs(3);
lhs4 = lhs(4);
lhs5 = lhs(5);
lhs6 = lhs(6);
lhs7 = lhs(7);

rhs1 = rhs(1);
rhs2 = rhs(2);
rhs3 = rhs(3);

t2 = lhs4.*rhs1;
t3 = lhs5.*rhs2;
t4 = lhs6.*rhs3;
t5 = t2+t3+t4;
t6 = lhs5.*rhs1;
t7 = lhs7.*rhs3;
t17 = lhs4.*rhs2;
t8 = t6+t7-t17;
t9 = lhs6.*rhs2;
t10 = lhs7.*rhs1;
t16 = lhs5.*rhs3;
t11 = t9+t10-t16;
t12 = lhs4.*rhs3;
t13 = lhs7.*rhs2;
t15 = lhs6.*rhs1;
t14 = t12+t13-t15;
out1 = [lhs1+lhs4.*t5-lhs5.*t8+lhs7.*t11+lhs6.*t14;lhs2+lhs5.*t5+lhs4.*t8-lhs6.*t11+lhs7.*t14;lhs3+lhs6.*t5+lhs7.*t8+lhs5.*t11-lhs4.*t14];
