function su2_ = exp_su2(phi)
%EXP_SU2
%    SU2_ = EXP_SU2(C_THETA2,PHI1,PHI2,PHI3,S_THETA2,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Feb-2019 15:55:22

theta = norm(phi);
s_theta2 = sin(theta/2);
c_theta2 = cos(theta/2);
phi1 = phi(1);
phi2 = phi(2);
phi3 = phi(3);

t2 = 1.0./theta;
su2_ = [-phi1.*s_theta2.*t2;-phi2.*s_theta2.*t2;-phi3.*s_theta2.*t2;c_theta2];
