function se3_ = exp_se3(screw_)
%EXP_SE3
%    SE3_ = EXP_SE3(C_THETA,PHI1,PHI2,PHI3,RHO1,RHO2,RHO3,S_THETA,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Feb-2019 15:15:38

rho = screw_(1:3);
phi = screw_(4:6);
theta = norm(phi);
% theta = sqrt(phi(1)^2 + phi(2)^2 + phi(3)^2);

rho1 = rho(1);
rho2 = rho(2);
rho3 = rho(3);
phi1 = phi(1);
phi2 = phi(2);
phi3 = phi(3);

c_theta = cos(theta);
s_theta = sin(theta);

t2 = 1.0./theta.^2;
t3 = c_theta-1.0;
t4 = 1.0./theta;
t5 = phi2.^2;
t6 = phi3.^2;
t7 = t5+t6;
t8 = 1.0./theta.^3;
t9 = s_theta-theta;
t10 = phi1.^2;
t11 = t6+t10;
t12 = phi3.*t2.*t3;
t13 = phi2.*s_theta.*t4;
t14 = t5+t10;
t15 = phi2.*t2.*t3;
t16 = phi1.*phi3.*t8.*t9;
t17 = phi1.*t2.*t3;
se3_ = reshape([t2.*t3.*t7+1.0,phi3.*s_theta.*t4-phi1.*phi2.*t2.*t3,-t13-phi1.*phi3.*t2.*t3,0.0,-phi3.*s_theta.*t4-phi1.*phi2.*t2.*t3,t2.*t3.*t11+1.0,phi1.*s_theta.*t4-phi2.*phi3.*t2.*t3,0.0,t13-phi1.*phi3.*t2.*t3,-phi1.*s_theta.*t4-phi2.*phi3.*t2.*t3,t2.*t3.*t14+1.0,0.0,-rho3.*(t15+t16)+rho2.*(t12-phi1.*phi2.*t8.*t9)+rho1.*(t7.*t8.*t9+1.0),-rho1.*(t12+phi1.*phi2.*t8.*t9)+rho3.*(t17-phi2.*phi3.*t8.*t9)+rho2.*(t8.*t9.*t11+1.0),rho1.*(t15-t16)-rho2.*(t17+phi2.*phi3.*t8.*t9)+rho3.*(t8.*t9.*t14+1.0),1.0],[4,4]);
