function so3_ = exp_so3(phi)
%EXP_SO3
%    SO3_ = EXP_SO3(C_THETA,PHI1,PHI2,PHI3,S_THETA,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Feb-2019 15:05:29

theta = norm(phi);

if (theta) < 2.5e-6
    so3_ = eye(3);
else
    c_theta = cos(theta);
    s_theta = sin(theta);
    phi_cross_mat = get_cross_mat(phi);
    so3_ = eye(3) + s_theta/theta*phi_cross_mat + ...
        (1 - c_theta)/theta^2*phi_cross_mat*phi_cross_mat;
end