function prod = quat_product(lhs, rhs)
%QUAT_PRODUCT
%    PROD = QUAT_PRODUCT(LHS1,LHS2,LHS3,LHS4,RHS1,RHS2,RHS3,RHS4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Feb-2019 12:31:44

lhs1 = lhs(1);
lhs2 = lhs(2);
lhs3 = lhs(3);
lhs4 = lhs(4);

rhs1 = rhs(1);
rhs2 = rhs(2);
rhs3 = rhs(3);
rhs4 = rhs(4);

prod = [lhs1.*rhs4-lhs2.*rhs3+lhs3.*rhs2+lhs4.*rhs1;lhs1.*rhs3-lhs3.*rhs1+lhs2.*rhs4+lhs4.*rhs2;-lhs1.*rhs2+lhs2.*rhs1+lhs3.*rhs4+lhs4.*rhs3;-lhs1.*rhs1-lhs2.*rhs2-lhs3.*rhs3+lhs4.*rhs4];
